#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# check types globally
npm lint:types

# run linters for changed files
npm lint-staged

# check global circular-deps
npm check:circular-deps

# run all tests
npm test
