name: Build and Test React Application

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ develop ]

jobs:
  install_node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

  verify:
    runs-on: ubuntu-latest

    needs: install_node

    strategy:
      matrix:
        node-version: [18.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
# complete here verification steps with linter, prettier, and circular

    unit-tests:
      runs-on: ubuntu-latest

      needs: verify

      strategy:
        matrix:
          node-version: [ 18.x ]

        run: |
          npm ci
          npm test
          npm run build --if-present
